/**
 * This file is autogenerated by Scaffold-Stark.
 * You should not edit it manually or your changes might be overwritten.
 */

const deployedContracts = {
  devnet: {
    StarkPlayERC20: {
      address:
        "0x226607a1df9bb3d0c1710ec0abb58320c601e2b4d5d467f513c53516a67d866",
      abi: [
        {
          type: "impl",
          name: "MintableImpl",
          interface_name: "contracts::StarkPlayERC20::IMintable",
        },
        {
          type: "struct",
          name: "core::integer::u256",
          members: [
            {
              name: "low",
              type: "core::integer::u128",
            },
            {
              name: "high",
              type: "core::integer::u128",
            },
          ],
        },
        {
          type: "interface",
          name: "contracts::StarkPlayERC20::IMintable",
          items: [
            {
              type: "function",
              name: "mint",
              inputs: [
                {
                  name: "recipient",
                  type: "core::starknet::contract_address::ContractAddress",
                },
                {
                  name: "amount",
                  type: "core::integer::u256",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "grant_minter_role",
              inputs: [
                {
                  name: "minter",
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "revoke_minter_role",
              inputs: [
                {
                  name: "minter",
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "set_minter_allowance",
              inputs: [
                {
                  name: "minter",
                  type: "core::starknet::contract_address::ContractAddress",
                },
                {
                  name: "allowance",
                  type: "core::integer::u256",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "get_minter_allowance",
              inputs: [
                {
                  name: "minter",
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              outputs: [
                {
                  type: "core::integer::u256",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "get_authorized_minters",
              inputs: [],
              outputs: [
                {
                  type: "core::array::Array::<core::starknet::contract_address::ContractAddress>",
                },
              ],
              state_mutability: "view",
            },
          ],
        },
        {
          type: "impl",
          name: "BurnableImpl",
          interface_name: "contracts::StarkPlayERC20::IBurnable",
        },
        {
          type: "interface",
          name: "contracts::StarkPlayERC20::IBurnable",
          items: [
            {
              type: "function",
              name: "burn",
              inputs: [
                {
                  name: "amount",
                  type: "core::integer::u256",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "burn_from",
              inputs: [
                {
                  name: "account",
                  type: "core::starknet::contract_address::ContractAddress",
                },
                {
                  name: "amount",
                  type: "core::integer::u256",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "grant_burner_role",
              inputs: [
                {
                  name: "burner",
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "revoke_burner_role",
              inputs: [
                {
                  name: "burner",
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "set_burner_allowance",
              inputs: [
                {
                  name: "burner",
                  type: "core::starknet::contract_address::ContractAddress",
                },
                {
                  name: "allowance",
                  type: "core::integer::u256",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "get_burner_allowance",
              inputs: [
                {
                  name: "burner",
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              outputs: [
                {
                  type: "core::integer::u256",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "get_authorized_burners",
              inputs: [],
              outputs: [
                {
                  type: "core::array::Array::<core::starknet::contract_address::ContractAddress>",
                },
              ],
              state_mutability: "view",
            },
          ],
        },
        {
          type: "impl",
          name: "PrizeTokenImpl",
          interface_name: "contracts::StarkPlayERC20::IPrizeToken",
        },
        {
          type: "interface",
          name: "contracts::StarkPlayERC20::IPrizeToken",
          items: [
            {
              type: "function",
              name: "assign_prize_tokens",
              inputs: [
                {
                  name: "recipient",
                  type: "core::starknet::contract_address::ContractAddress",
                },
                {
                  name: "amount",
                  type: "core::integer::u256",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "get_prize_balance",
              inputs: [
                {
                  name: "account",
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              outputs: [
                {
                  type: "core::integer::u256",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "grant_prize_assigner_role",
              inputs: [
                {
                  name: "assigner",
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "revoke_prize_assigner_role",
              inputs: [
                {
                  name: "assigner",
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
          ],
        },
        {
          type: "impl",
          name: "UpgradeableImpl",
          interface_name: "openzeppelin_upgrades::interface::IUpgradeable",
        },
        {
          type: "interface",
          name: "openzeppelin_upgrades::interface::IUpgradeable",
          items: [
            {
              type: "function",
              name: "upgrade",
              inputs: [
                {
                  name: "new_class_hash",
                  type: "core::starknet::class_hash::ClassHash",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
          ],
        },
        {
          type: "impl",
          name: "TestingHelpers",
          interface_name: "contracts::StarkPlayERC20::ITestingHelpers",
        },
        {
          type: "interface",
          name: "contracts::StarkPlayERC20::ITestingHelpers",
          items: [
            {
              type: "function",
              name: "getTotalSupply",
              inputs: [],
              outputs: [
                {
                  type: "core::integer::u256",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "getAllAllowances",
              inputs: [
                {
                  name: "account",
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              outputs: [
                {
                  type: "(core::integer::u256, core::integer::u256)",
                },
              ],
              state_mutability: "view",
            },
          ],
        },
        {
          type: "impl",
          name: "ERC20MixinImpl",
          interface_name: "openzeppelin_token::erc20::interface::IERC20Mixin",
        },
        {
          type: "enum",
          name: "core::bool",
          variants: [
            {
              name: "False",
              type: "()",
            },
            {
              name: "True",
              type: "()",
            },
          ],
        },
        {
          type: "struct",
          name: "core::byte_array::ByteArray",
          members: [
            {
              name: "data",
              type: "core::array::Array::<core::bytes_31::bytes31>",
            },
            {
              name: "pending_word",
              type: "core::felt252",
            },
            {
              name: "pending_word_len",
              type: "core::integer::u32",
            },
          ],
        },
        {
          type: "interface",
          name: "openzeppelin_token::erc20::interface::IERC20Mixin",
          items: [
            {
              type: "function",
              name: "total_supply",
              inputs: [],
              outputs: [
                {
                  type: "core::integer::u256",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "balance_of",
              inputs: [
                {
                  name: "account",
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              outputs: [
                {
                  type: "core::integer::u256",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "allowance",
              inputs: [
                {
                  name: "owner",
                  type: "core::starknet::contract_address::ContractAddress",
                },
                {
                  name: "spender",
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              outputs: [
                {
                  type: "core::integer::u256",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "transfer",
              inputs: [
                {
                  name: "recipient",
                  type: "core::starknet::contract_address::ContractAddress",
                },
                {
                  name: "amount",
                  type: "core::integer::u256",
                },
              ],
              outputs: [
                {
                  type: "core::bool",
                },
              ],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "transfer_from",
              inputs: [
                {
                  name: "sender",
                  type: "core::starknet::contract_address::ContractAddress",
                },
                {
                  name: "recipient",
                  type: "core::starknet::contract_address::ContractAddress",
                },
                {
                  name: "amount",
                  type: "core::integer::u256",
                },
              ],
              outputs: [
                {
                  type: "core::bool",
                },
              ],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "approve",
              inputs: [
                {
                  name: "spender",
                  type: "core::starknet::contract_address::ContractAddress",
                },
                {
                  name: "amount",
                  type: "core::integer::u256",
                },
              ],
              outputs: [
                {
                  type: "core::bool",
                },
              ],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "name",
              inputs: [],
              outputs: [
                {
                  type: "core::byte_array::ByteArray",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "symbol",
              inputs: [],
              outputs: [
                {
                  type: "core::byte_array::ByteArray",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "decimals",
              inputs: [],
              outputs: [
                {
                  type: "core::integer::u8",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "totalSupply",
              inputs: [],
              outputs: [
                {
                  type: "core::integer::u256",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "balanceOf",
              inputs: [
                {
                  name: "account",
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              outputs: [
                {
                  type: "core::integer::u256",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "transferFrom",
              inputs: [
                {
                  name: "sender",
                  type: "core::starknet::contract_address::ContractAddress",
                },
                {
                  name: "recipient",
                  type: "core::starknet::contract_address::ContractAddress",
                },
                {
                  name: "amount",
                  type: "core::integer::u256",
                },
              ],
              outputs: [
                {
                  type: "core::bool",
                },
              ],
              state_mutability: "external",
            },
          ],
        },
        {
          type: "impl",
          name: "PausableImpl",
          interface_name: "openzeppelin_security::interface::IPausable",
        },
        {
          type: "interface",
          name: "openzeppelin_security::interface::IPausable",
          items: [
            {
              type: "function",
              name: "is_paused",
              inputs: [],
              outputs: [
                {
                  type: "core::bool",
                },
              ],
              state_mutability: "view",
            },
          ],
        },
        {
          type: "impl",
          name: "AccessControlMixinImpl",
          interface_name:
            "openzeppelin_access::accesscontrol::interface::AccessControlABI",
        },
        {
          type: "interface",
          name: "openzeppelin_access::accesscontrol::interface::AccessControlABI",
          items: [
            {
              type: "function",
              name: "has_role",
              inputs: [
                {
                  name: "role",
                  type: "core::felt252",
                },
                {
                  name: "account",
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              outputs: [
                {
                  type: "core::bool",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "get_role_admin",
              inputs: [
                {
                  name: "role",
                  type: "core::felt252",
                },
              ],
              outputs: [
                {
                  type: "core::felt252",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "grant_role",
              inputs: [
                {
                  name: "role",
                  type: "core::felt252",
                },
                {
                  name: "account",
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "revoke_role",
              inputs: [
                {
                  name: "role",
                  type: "core::felt252",
                },
                {
                  name: "account",
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "renounce_role",
              inputs: [
                {
                  name: "role",
                  type: "core::felt252",
                },
                {
                  name: "account",
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "hasRole",
              inputs: [
                {
                  name: "role",
                  type: "core::felt252",
                },
                {
                  name: "account",
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              outputs: [
                {
                  type: "core::bool",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "getRoleAdmin",
              inputs: [
                {
                  name: "role",
                  type: "core::felt252",
                },
              ],
              outputs: [
                {
                  type: "core::felt252",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "grantRole",
              inputs: [
                {
                  name: "role",
                  type: "core::felt252",
                },
                {
                  name: "account",
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "revokeRole",
              inputs: [
                {
                  name: "role",
                  type: "core::felt252",
                },
                {
                  name: "account",
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "renounceRole",
              inputs: [
                {
                  name: "role",
                  type: "core::felt252",
                },
                {
                  name: "account",
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "supports_interface",
              inputs: [
                {
                  name: "interface_id",
                  type: "core::felt252",
                },
              ],
              outputs: [
                {
                  type: "core::bool",
                },
              ],
              state_mutability: "view",
            },
          ],
        },
        {
          type: "constructor",
          name: "constructor",
          inputs: [
            {
              name: "recipient",
              type: "core::starknet::contract_address::ContractAddress",
            },
            {
              name: "admin",
              type: "core::starknet::contract_address::ContractAddress",
            },
          ],
        },
        {
          type: "event",
          name: "openzeppelin_token::erc20::erc20::ERC20Component::Transfer",
          kind: "struct",
          members: [
            {
              name: "from",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "key",
            },
            {
              name: "to",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "key",
            },
            {
              name: "value",
              type: "core::integer::u256",
              kind: "data",
            },
          ],
        },
        {
          type: "event",
          name: "openzeppelin_token::erc20::erc20::ERC20Component::Approval",
          kind: "struct",
          members: [
            {
              name: "owner",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "key",
            },
            {
              name: "spender",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "key",
            },
            {
              name: "value",
              type: "core::integer::u256",
              kind: "data",
            },
          ],
        },
        {
          type: "event",
          name: "openzeppelin_token::erc20::erc20::ERC20Component::Event",
          kind: "enum",
          variants: [
            {
              name: "Transfer",
              type: "openzeppelin_token::erc20::erc20::ERC20Component::Transfer",
              kind: "nested",
            },
            {
              name: "Approval",
              type: "openzeppelin_token::erc20::erc20::ERC20Component::Approval",
              kind: "nested",
            },
          ],
        },
        {
          type: "event",
          name: "openzeppelin_security::pausable::PausableComponent::Paused",
          kind: "struct",
          members: [
            {
              name: "account",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "data",
            },
          ],
        },
        {
          type: "event",
          name: "openzeppelin_security::pausable::PausableComponent::Unpaused",
          kind: "struct",
          members: [
            {
              name: "account",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "data",
            },
          ],
        },
        {
          type: "event",
          name: "openzeppelin_security::pausable::PausableComponent::Event",
          kind: "enum",
          variants: [
            {
              name: "Paused",
              type: "openzeppelin_security::pausable::PausableComponent::Paused",
              kind: "nested",
            },
            {
              name: "Unpaused",
              type: "openzeppelin_security::pausable::PausableComponent::Unpaused",
              kind: "nested",
            },
          ],
        },
        {
          type: "event",
          name: "openzeppelin_access::accesscontrol::accesscontrol::AccessControlComponent::RoleGranted",
          kind: "struct",
          members: [
            {
              name: "role",
              type: "core::felt252",
              kind: "data",
            },
            {
              name: "account",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "data",
            },
            {
              name: "sender",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "data",
            },
          ],
        },
        {
          type: "event",
          name: "openzeppelin_access::accesscontrol::accesscontrol::AccessControlComponent::RoleRevoked",
          kind: "struct",
          members: [
            {
              name: "role",
              type: "core::felt252",
              kind: "data",
            },
            {
              name: "account",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "data",
            },
            {
              name: "sender",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "data",
            },
          ],
        },
        {
          type: "event",
          name: "openzeppelin_access::accesscontrol::accesscontrol::AccessControlComponent::RoleAdminChanged",
          kind: "struct",
          members: [
            {
              name: "role",
              type: "core::felt252",
              kind: "data",
            },
            {
              name: "previous_admin_role",
              type: "core::felt252",
              kind: "data",
            },
            {
              name: "new_admin_role",
              type: "core::felt252",
              kind: "data",
            },
          ],
        },
        {
          type: "event",
          name: "openzeppelin_access::accesscontrol::accesscontrol::AccessControlComponent::Event",
          kind: "enum",
          variants: [
            {
              name: "RoleGranted",
              type: "openzeppelin_access::accesscontrol::accesscontrol::AccessControlComponent::RoleGranted",
              kind: "nested",
            },
            {
              name: "RoleRevoked",
              type: "openzeppelin_access::accesscontrol::accesscontrol::AccessControlComponent::RoleRevoked",
              kind: "nested",
            },
            {
              name: "RoleAdminChanged",
              type: "openzeppelin_access::accesscontrol::accesscontrol::AccessControlComponent::RoleAdminChanged",
              kind: "nested",
            },
          ],
        },
        {
          type: "event",
          name: "openzeppelin_introspection::src5::SRC5Component::Event",
          kind: "enum",
          variants: [],
        },
        {
          type: "event",
          name: "openzeppelin_upgrades::upgradeable::UpgradeableComponent::Upgraded",
          kind: "struct",
          members: [
            {
              name: "class_hash",
              type: "core::starknet::class_hash::ClassHash",
              kind: "data",
            },
          ],
        },
        {
          type: "event",
          name: "openzeppelin_upgrades::upgradeable::UpgradeableComponent::Event",
          kind: "enum",
          variants: [
            {
              name: "Upgraded",
              type: "openzeppelin_upgrades::upgradeable::UpgradeableComponent::Upgraded",
              kind: "nested",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::StarkPlayERC20::StarkPlayERC20::Burn",
          kind: "struct",
          members: [
            {
              name: "burner",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "key",
            },
            {
              name: "amount",
              type: "core::integer::u256",
              kind: "key",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::StarkPlayERC20::StarkPlayERC20::Mint",
          kind: "struct",
          members: [
            {
              name: "recipient",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "key",
            },
            {
              name: "amount",
              type: "core::integer::u256",
              kind: "key",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::StarkPlayERC20::StarkPlayERC20::MinterAllowanceSet",
          kind: "struct",
          members: [
            {
              name: "minter",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "key",
            },
            {
              name: "allowance",
              type: "core::integer::u256",
              kind: "key",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::StarkPlayERC20::StarkPlayERC20::BurnerAllowanceSet",
          kind: "struct",
          members: [
            {
              name: "burner",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "key",
            },
            {
              name: "allowance",
              type: "core::integer::u256",
              kind: "key",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::StarkPlayERC20::StarkPlayERC20::PrizeTokensAssigned",
          kind: "struct",
          members: [
            {
              name: "recipient",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "key",
            },
            {
              name: "amount",
              type: "core::integer::u256",
              kind: "key",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::StarkPlayERC20::StarkPlayERC20::Event",
          kind: "enum",
          variants: [
            {
              name: "ERC20Event",
              type: "openzeppelin_token::erc20::erc20::ERC20Component::Event",
              kind: "flat",
            },
            {
              name: "PausableEvent",
              type: "openzeppelin_security::pausable::PausableComponent::Event",
              kind: "flat",
            },
            {
              name: "AccessControlEvent",
              type: "openzeppelin_access::accesscontrol::accesscontrol::AccessControlComponent::Event",
              kind: "flat",
            },
            {
              name: "SRC5Event",
              type: "openzeppelin_introspection::src5::SRC5Component::Event",
              kind: "flat",
            },
            {
              name: "UpgradeableEvent",
              type: "openzeppelin_upgrades::upgradeable::UpgradeableComponent::Event",
              kind: "flat",
            },
            {
              name: "Burn",
              type: "contracts::StarkPlayERC20::StarkPlayERC20::Burn",
              kind: "nested",
            },
            {
              name: "Mint",
              type: "contracts::StarkPlayERC20::StarkPlayERC20::Mint",
              kind: "nested",
            },
            {
              name: "MinterAllowanceSet",
              type: "contracts::StarkPlayERC20::StarkPlayERC20::MinterAllowanceSet",
              kind: "nested",
            },
            {
              name: "BurnerAllowanceSet",
              type: "contracts::StarkPlayERC20::StarkPlayERC20::BurnerAllowanceSet",
              kind: "nested",
            },
            {
              name: "PrizeTokensAssigned",
              type: "contracts::StarkPlayERC20::StarkPlayERC20::PrizeTokensAssigned",
              kind: "nested",
            },
          ],
        },
      ],
      classHash:
        "0x1db26668046de7c00fed257f34a0dad314a19a1fc8cc6816381ab7defec22b0",
    },
    StarkPlayVault: {
      address:
        "0x51142ea799b634434226889fb52499463219f4a092232e2c8f3fdeb7865dc37",
      abi: [
        {
          type: "impl",
          name: "StarkPlayVaultImpl",
          interface_name: "contracts::StarkPlayVault::IStarkPlayVault",
        },
        {
          type: "struct",
          name: "core::integer::u256",
          members: [
            {
              name: "low",
              type: "core::integer::u128",
            },
            {
              name: "high",
              type: "core::integer::u128",
            },
          ],
        },
        {
          type: "enum",
          name: "core::bool",
          variants: [
            {
              name: "False",
              type: "()",
            },
            {
              name: "True",
              type: "()",
            },
          ],
        },
        {
          type: "interface",
          name: "contracts::StarkPlayVault::IStarkPlayVault",
          items: [
            {
              type: "function",
              name: "GetFeePercentage",
              inputs: [],
              outputs: [
                {
                  type: "core::integer::u64",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "GetFeePercentagePrizesConverted",
              inputs: [],
              outputs: [
                {
                  type: "core::integer::u64",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "GetAccumulatedPrizeConversionFees",
              inputs: [],
              outputs: [
                {
                  type: "core::integer::u256",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "get_mint_limit",
              inputs: [],
              outputs: [
                {
                  type: "core::integer::u256",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "get_burn_limit",
              inputs: [],
              outputs: [
                {
                  type: "core::integer::u256",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "get_accumulated_fee",
              inputs: [],
              outputs: [
                {
                  type: "core::integer::u256",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "get_total_starkplay_minted",
              inputs: [],
              outputs: [
                {
                  type: "core::integer::u256",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "get_total_strk_stored",
              inputs: [],
              outputs: [
                {
                  type: "core::integer::u256",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "get_total_starkplay_burned",
              inputs: [],
              outputs: [
                {
                  type: "core::integer::u256",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "set_fee",
              inputs: [
                {
                  name: "new_fee",
                  type: "core::integer::u64",
                },
              ],
              outputs: [
                {
                  type: "core::bool",
                },
              ],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "setMintLimit",
              inputs: [
                {
                  name: "new_limit",
                  type: "core::integer::u256",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "setBurnLimit",
              inputs: [
                {
                  name: "new_limit",
                  type: "core::integer::u256",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "setFeePercentage",
              inputs: [
                {
                  name: "new_fee",
                  type: "core::integer::u64",
                },
              ],
              outputs: [
                {
                  type: "core::bool",
                },
              ],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "setFeePercentagePrizesConverted",
              inputs: [
                {
                  name: "new_fee",
                  type: "core::integer::u64",
                },
              ],
              outputs: [
                {
                  type: "core::bool",
                },
              ],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "convert_to_strk",
              inputs: [
                {
                  name: "amount",
                  type: "core::integer::u256",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "mint_strk_play",
              inputs: [
                {
                  name: "user",
                  type: "core::starknet::contract_address::ContractAddress",
                },
                {
                  name: "amount",
                  type: "core::integer::u256",
                },
              ],
              outputs: [
                {
                  type: "core::bool",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "buySTRKP",
              inputs: [
                {
                  name: "user",
                  type: "core::starknet::contract_address::ContractAddress",
                },
                {
                  name: "amountSTRK",
                  type: "core::integer::u256",
                },
              ],
              outputs: [
                {
                  type: "core::bool",
                },
              ],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "pause",
              inputs: [],
              outputs: [
                {
                  type: "core::bool",
                },
              ],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "unpause",
              inputs: [],
              outputs: [
                {
                  type: "core::bool",
                },
              ],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "is_paused",
              inputs: [],
              outputs: [
                {
                  type: "core::bool",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "withdrawGeneralFees",
              inputs: [
                {
                  name: "recipient",
                  type: "core::starknet::contract_address::ContractAddress",
                },
                {
                  name: "amount",
                  type: "core::integer::u256",
                },
              ],
              outputs: [
                {
                  type: "core::bool",
                },
              ],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "withdrawPrizeConversionFees",
              inputs: [
                {
                  name: "recipient",
                  type: "core::starknet::contract_address::ContractAddress",
                },
                {
                  name: "amount",
                  type: "core::integer::u256",
                },
              ],
              outputs: [
                {
                  type: "core::bool",
                },
              ],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "set_treasury_address",
              inputs: [
                {
                  name: "treasury",
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              outputs: [
                {
                  type: "core::bool",
                },
              ],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "get_treasury_address",
              inputs: [],
              outputs: [
                {
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "set_treasury_address",
              inputs: [
                {
                  name: "treasury",
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              outputs: [
                {
                  type: "core::bool",
                },
              ],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "get_treasury_address",
              inputs: [],
              outputs: [
                {
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "update_total_strk_stored",
              inputs: [
                {
                  name: "amount",
                  type: "core::integer::u256",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
          ],
        },
        {
          type: "impl",
          name: "OwnableImpl",
          interface_name: "openzeppelin_access::ownable::interface::IOwnable",
        },
        {
          type: "interface",
          name: "openzeppelin_access::ownable::interface::IOwnable",
          items: [
            {
              type: "function",
              name: "owner",
              inputs: [],
              outputs: [
                {
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "transfer_ownership",
              inputs: [
                {
                  name: "new_owner",
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "renounce_ownership",
              inputs: [],
              outputs: [],
              state_mutability: "external",
            },
          ],
        },
        {
          type: "constructor",
          name: "constructor",
          inputs: [
            {
              name: "owner",
              type: "core::starknet::contract_address::ContractAddress",
            },
            {
              name: "starkPlayToken",
              type: "core::starknet::contract_address::ContractAddress",
            },
            {
              name: "feePercentage",
              type: "core::integer::u64",
            },
          ],
        },
        {
          type: "event",
          name: "openzeppelin_access::ownable::ownable::OwnableComponent::OwnershipTransferred",
          kind: "struct",
          members: [
            {
              name: "previous_owner",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "key",
            },
            {
              name: "new_owner",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "key",
            },
          ],
        },
        {
          type: "event",
          name: "openzeppelin_access::ownable::ownable::OwnableComponent::OwnershipTransferStarted",
          kind: "struct",
          members: [
            {
              name: "previous_owner",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "key",
            },
            {
              name: "new_owner",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "key",
            },
          ],
        },
        {
          type: "event",
          name: "openzeppelin_access::ownable::ownable::OwnableComponent::Event",
          kind: "enum",
          variants: [
            {
              name: "OwnershipTransferred",
              type: "openzeppelin_access::ownable::ownable::OwnableComponent::OwnershipTransferred",
              kind: "nested",
            },
            {
              name: "OwnershipTransferStarted",
              type: "openzeppelin_access::ownable::ownable::OwnableComponent::OwnershipTransferStarted",
              kind: "nested",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::StarkPlayVault::StarkPlayVault::STRKDeposited",
          kind: "struct",
          members: [
            {
              name: "user",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "key",
            },
            {
              name: "amount",
              type: "core::integer::u256",
              kind: "key",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::StarkPlayVault::StarkPlayVault::STRKWithdrawn",
          kind: "struct",
          members: [
            {
              name: "user",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "key",
            },
            {
              name: "amount",
              type: "core::integer::u256",
              kind: "key",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::StarkPlayVault::StarkPlayVault::StarkPlayMinted",
          kind: "struct",
          members: [
            {
              name: "user",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "key",
            },
            {
              name: "amount",
              type: "core::integer::u256",
              kind: "key",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::StarkPlayVault::StarkPlayVault::StarkPlayBurned",
          kind: "struct",
          members: [
            {
              name: "user",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "key",
            },
            {
              name: "amount",
              type: "core::integer::u256",
              kind: "key",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::StarkPlayVault::StarkPlayVault::Paused",
          kind: "struct",
          members: [
            {
              name: "admin",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "key",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::StarkPlayVault::StarkPlayVault::Unpaused",
          kind: "struct",
          members: [
            {
              name: "admin",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "key",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::StarkPlayVault::StarkPlayVault::StarkPlayBurnedByOwner",
          kind: "struct",
          members: [
            {
              name: "owner",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "key",
            },
            {
              name: "user",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "key",
            },
            {
              name: "amount",
              type: "core::integer::u256",
              kind: "key",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::StarkPlayVault::StarkPlayVault::FeeCollected",
          kind: "struct",
          members: [
            {
              name: "user",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "key",
            },
            {
              name: "amount",
              type: "core::integer::u256",
              kind: "key",
            },
            {
              name: "accumulatedFee",
              type: "core::integer::u256",
              kind: "data",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::StarkPlayVault::StarkPlayVault::ConvertedToSTRK",
          kind: "struct",
          members: [
            {
              name: "user",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "key",
            },
            {
              name: "amount",
              type: "core::integer::u256",
              kind: "key",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::StarkPlayVault::StarkPlayVault::MintLimitUpdated",
          kind: "struct",
          members: [
            {
              name: "new_mint_limit",
              type: "core::integer::u256",
              kind: "data",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::StarkPlayVault::StarkPlayVault::BurnLimitUpdated",
          kind: "struct",
          members: [
            {
              name: "new_burn_limit",
              type: "core::integer::u256",
              kind: "data",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::StarkPlayVault::StarkPlayVault::SetFeePercentage",
          kind: "struct",
          members: [
            {
              name: "owner",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "key",
            },
            {
              name: "old_fee",
              type: "core::integer::u64",
              kind: "data",
            },
            {
              name: "new_fee",
              type: "core::integer::u64",
              kind: "data",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::StarkPlayVault::StarkPlayVault::SetFeePercentagePrizesConverted",
          kind: "struct",
          members: [
            {
              name: "owner",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "key",
            },
            {
              name: "old_fee",
              type: "core::integer::u64",
              kind: "data",
            },
            {
              name: "new_fee",
              type: "core::integer::u64",
              kind: "data",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::StarkPlayVault::StarkPlayVault::FeeUpdated",
          kind: "struct",
          members: [
            {
              name: "admin",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "key",
            },
            {
              name: "old_fee",
              type: "core::integer::u64",
              kind: "data",
            },
            {
              name: "new_fee",
              type: "core::integer::u64",
              kind: "data",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::StarkPlayVault::StarkPlayVault::GeneralFeesWithdrawn",
          kind: "struct",
          members: [
            {
              name: "recipient",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "key",
            },
            {
              name: "amount",
              type: "core::integer::u256",
              kind: "key",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::StarkPlayVault::StarkPlayVault::PrizeConversionFeesWithdrawn",
          kind: "struct",
          members: [
            {
              name: "recipient",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "key",
            },
            {
              name: "amount",
              type: "core::integer::u256",
              kind: "key",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::StarkPlayVault::StarkPlayVault::TreasuryFeeTransferred",
          kind: "struct",
          members: [
            {
              name: "user",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "key",
            },
            {
              name: "amount",
              type: "core::integer::u256",
              kind: "key",
            },
            {
              name: "treasury",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "data",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::StarkPlayVault::StarkPlayVault::TreasuryFeeTransferred",
          kind: "struct",
          members: [
            {
              name: "user",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "key",
            },
            {
              name: "amount",
              type: "core::integer::u256",
              kind: "key",
            },
            {
              name: "treasury",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "data",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::StarkPlayVault::StarkPlayVault::Event",
          kind: "enum",
          variants: [
            {
              name: "OwnableEvent",
              type: "openzeppelin_access::ownable::ownable::OwnableComponent::Event",
              kind: "flat",
            },
            {
              name: "STRKDeposited",
              type: "contracts::StarkPlayVault::StarkPlayVault::STRKDeposited",
              kind: "nested",
            },
            {
              name: "STRKWithdrawn",
              type: "contracts::StarkPlayVault::StarkPlayVault::STRKWithdrawn",
              kind: "nested",
            },
            {
              name: "StarkPlayMinted",
              type: "contracts::StarkPlayVault::StarkPlayVault::StarkPlayMinted",
              kind: "nested",
            },
            {
              name: "StarkPlayBurned",
              type: "contracts::StarkPlayVault::StarkPlayVault::StarkPlayBurned",
              kind: "nested",
            },
            {
              name: "Paused",
              type: "contracts::StarkPlayVault::StarkPlayVault::Paused",
              kind: "nested",
            },
            {
              name: "Unpaused",
              type: "contracts::StarkPlayVault::StarkPlayVault::Unpaused",
              kind: "nested",
            },
            {
              name: "StarkPlayBurnedByOwner",
              type: "contracts::StarkPlayVault::StarkPlayVault::StarkPlayBurnedByOwner",
              kind: "nested",
            },
            {
              name: "FeeCollected",
              type: "contracts::StarkPlayVault::StarkPlayVault::FeeCollected",
              kind: "nested",
            },
            {
              name: "ConvertedToSTRK",
              type: "contracts::StarkPlayVault::StarkPlayVault::ConvertedToSTRK",
              kind: "nested",
            },
            {
              name: "MintLimitUpdated",
              type: "contracts::StarkPlayVault::StarkPlayVault::MintLimitUpdated",
              kind: "nested",
            },
            {
              name: "BurnLimitUpdated",
              type: "contracts::StarkPlayVault::StarkPlayVault::BurnLimitUpdated",
              kind: "nested",
            },
            {
              name: "SetFeePercentage",
              type: "contracts::StarkPlayVault::StarkPlayVault::SetFeePercentage",
              kind: "nested",
            },
            {
              name: "SetFeePercentagePrizesConverted",
              type: "contracts::StarkPlayVault::StarkPlayVault::SetFeePercentagePrizesConverted",
              kind: "nested",
            },
            {
              name: "FeeUpdated",
              type: "contracts::StarkPlayVault::StarkPlayVault::FeeUpdated",
              kind: "nested",
            },
            {
              name: "GeneralFeesWithdrawn",
              type: "contracts::StarkPlayVault::StarkPlayVault::GeneralFeesWithdrawn",
              kind: "nested",
            },
            {
              name: "PrizeConversionFeesWithdrawn",
              type: "contracts::StarkPlayVault::StarkPlayVault::PrizeConversionFeesWithdrawn",
              kind: "nested",
            },
            {
              name: "TreasuryFeeTransferred",
              type: "contracts::StarkPlayVault::StarkPlayVault::TreasuryFeeTransferred",
              kind: "nested",
            },
            {
              name: "TreasuryFeeTransferred",
              type: "contracts::StarkPlayVault::StarkPlayVault::TreasuryFeeTransferred",
              kind: "nested",
            },
          ],
        },
      ],
      classHash:
        "0x1127ea2a6241450cb7d4fa483bce8f52140a66f8262a73f7bf1db85a55bb6a3",
    },
    Lottery: {
      address:
        "0x16064c51522e9a0da124120e839fd5c6947177c76804c308f0a447867a8cb5c",
      abi: [
        {
          type: "impl",
          name: "LotteryImpl",
          interface_name: "contracts::Lottery::ILottery",
        },
        {
          type: "struct",
          name: "core::integer::u256",
          members: [
            {
              name: "low",
              type: "core::integer::u128",
            },
            {
              name: "high",
              type: "core::integer::u128",
            },
          ],
        },
        {
          type: "enum",
          name: "core::bool",
          variants: [
            {
              name: "False",
              type: "()",
            },
            {
              name: "True",
              type: "()",
            },
          ],
        },
        {
          type: "struct",
          name: "contracts::Lottery::Ticket",
          members: [
            {
              name: "player",
              type: "core::starknet::contract_address::ContractAddress",
            },
            {
              name: "number1",
              type: "core::integer::u16",
            },
            {
              name: "number2",
              type: "core::integer::u16",
            },
            {
              name: "number3",
              type: "core::integer::u16",
            },
            {
              name: "number4",
              type: "core::integer::u16",
            },
            {
              name: "number5",
              type: "core::integer::u16",
            },
            {
              name: "claimed",
              type: "core::bool",
            },
            {
              name: "drawId",
              type: "core::integer::u64",
            },
            {
              name: "timestamp",
              type: "core::integer::u64",
            },
          ],
        },
        {
          type: "struct",
          name: "contracts::Lottery::JackpotEntry",
          members: [
            {
              name: "drawId",
              type: "core::integer::u64",
            },
            {
              name: "jackpotAmount",
              type: "core::integer::u256",
            },
            {
              name: "startTime",
              type: "core::integer::u64",
            },
            {
              name: "endTime",
              type: "core::integer::u64",
            },
            {
              name: "startBlock",
              type: "core::integer::u64",
            },
            {
              name: "endBlock",
              type: "core::integer::u64",
            },
            {
              name: "isActive",
              type: "core::bool",
            },
            {
              name: "isCompleted",
              type: "core::bool",
            },
          ],
        },
        {
          type: "interface",
          name: "contracts::Lottery::ILottery",
          items: [
            {
              type: "function",
              name: "Initialize",
              inputs: [
                {
                  name: "ticketPrice",
                  type: "core::integer::u256",
                },
                {
                  name: "accumulatedPrize",
                  type: "core::integer::u256",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "BuyTicket",
              inputs: [
                {
                  name: "drawId",
                  type: "core::integer::u64",
                },
                {
                  name: "numbers_array",
                  type: "core::array::Array::<core::array::Array::<core::integer::u16>>",
                  name: "numbers_array",
                  type: "core::array::Array::<core::array::Array::<core::integer::u16>>",
                },
                {
                  name: "quantity",
                  type: "core::integer::u8",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "DrawNumbers",
              inputs: [
                {
                  name: "drawId",
                  type: "core::integer::u64",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "ClaimPrize",
              inputs: [
                {
                  name: "drawId",
                  type: "core::integer::u64",
                },
                {
                  name: "ticketId",
                  type: "core::felt252",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "CheckMatches",
              inputs: [
                {
                  name: "drawId",
                  type: "core::integer::u64",
                },
                {
                  name: "number1",
                  type: "core::integer::u16",
                },
                {
                  name: "number2",
                  type: "core::integer::u16",
                },
                {
                  name: "number3",
                  type: "core::integer::u16",
                },
                {
                  name: "number4",
                  type: "core::integer::u16",
                },
                {
                  name: "number5",
                  type: "core::integer::u16",
                },
              ],
              outputs: [
                {
                  type: "core::integer::u8",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "CreateNewDraw",
              inputs: [
                {
                  name: "accumulatedPrize",
                  type: "core::integer::u256",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "SetTicketPrice",
              inputs: [
                {
                  name: "price",
                  type: "core::integer::u256",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "EmergencyResetReentrancyGuard",
              inputs: [],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "GetTicketPrice",
              inputs: [],
              outputs: [
                {
                  type: "core::integer::u256",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "GetAccumulatedPrize",
              inputs: [],
              outputs: [
                {
                  type: "core::integer::u256",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "GetFixedPrize",
              inputs: [
                {
                  name: "matches",
                  type: "core::integer::u8",
                },
              ],
              outputs: [
                {
                  type: "core::integer::u256",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "GetDrawStatus",
              inputs: [
                {
                  name: "drawId",
                  type: "core::integer::u64",
                },
              ],
              outputs: [
                {
                  type: "core::bool",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "GetBlocksRemaining",
              inputs: [
                {
                  name: "drawId",
                  type: "core::integer::u64",
                },
              ],
              outputs: [
                {
                  type: "core::integer::u64",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "IsDrawActive",
              inputs: [
                {
                  name: "drawId",
                  type: "core::integer::u64",
                },
              ],
              outputs: [
                {
                  type: "core::bool",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "GetUserTicketIds",
              inputs: [
                {
                  name: "drawId",
                  type: "core::integer::u64",
                },
                {
                  name: "player",
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              outputs: [
                {
                  type: "core::array::Array::<core::felt252>",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "GetUserTickets",
              inputs: [
                {
                  name: "drawId",
                  type: "core::integer::u64",
                },
                {
                  name: "player",
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              outputs: [
                {
                  type: "core::array::Array::<contracts::Lottery::Ticket>",
                },
              ],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "GetUserTicketsCount",
              inputs: [
                {
                  name: "drawId",
                  type: "core::integer::u64",
                },
                {
                  name: "player",
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              outputs: [
                {
                  type: "core::integer::u32",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "GetTicketInfo",
              inputs: [
                {
                  name: "drawId",
                  type: "core::integer::u64",
                },
                {
                  name: "ticketId",
                  type: "core::felt252",
                },
                {
                  name: "player",
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              outputs: [
                {
                  type: "contracts::Lottery::Ticket",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "GetTicketCurrentId",
              inputs: [],
              outputs: [
                {
                  type: "core::integer::u64",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "GetWinningNumbers",
              inputs: [
                {
                  name: "drawId",
                  type: "core::integer::u64",
                },
              ],
              outputs: [
                {
                  type: "core::array::Array::<core::integer::u16>",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "get_jackpot_history",
              inputs: [],
              outputs: [
                {
                  type: "core::array::Array::<contracts::Lottery::JackpotEntry>",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "GetTicketPlayer",
              inputs: [
                {
                  name: "drawId",
                  type: "core::integer::u64",
                },
                {
                  name: "ticketId",
                  type: "core::felt252",
                },
              ],
              outputs: [
                {
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "GetTicketNumbers",
              inputs: [
                {
                  name: "drawId",
                  type: "core::integer::u64",
                },
                {
                  name: "ticketId",
                  type: "core::felt252",
                },
              ],
              outputs: [
                {
                  type: "core::array::Array::<core::integer::u16>",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "GetTicketClaimed",
              inputs: [
                {
                  name: "drawId",
                  type: "core::integer::u64",
                },
                {
                  name: "ticketId",
                  type: "core::felt252",
                },
              ],
              outputs: [
                {
                  type: "core::bool",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "GetTicketDrawId",
              inputs: [
                {
                  name: "drawId",
                  type: "core::integer::u64",
                },
                {
                  name: "ticketId",
                  type: "core::felt252",
                },
              ],
              outputs: [
                {
                  type: "core::integer::u64",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "GetTicketTimestamp",
              inputs: [
                {
                  name: "drawId",
                  type: "core::integer::u64",
                },
                {
                  name: "ticketId",
                  type: "core::felt252",
                },
              ],
              outputs: [
                {
                  type: "core::integer::u64",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "GetJackpotEntryDrawId",
              inputs: [
                {
                  name: "drawId",
                  type: "core::integer::u64",
                },
              ],
              outputs: [
                {
                  type: "core::integer::u64",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "GetJackpotEntryAmount",
              inputs: [
                {
                  name: "drawId",
                  type: "core::integer::u64",
                },
              ],
              outputs: [
                {
                  type: "core::integer::u256",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "GetJackpotEntryStartTime",
              inputs: [
                {
                  name: "drawId",
                  type: "core::integer::u64",
                },
              ],
              outputs: [
                {
                  type: "core::integer::u64",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "GetJackpotEntryEndTime",
              inputs: [
                {
                  name: "drawId",
                  type: "core::integer::u64",
                },
              ],
              outputs: [
                {
                  type: "core::integer::u64",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "GetJackpotEntryStartBlock",
              inputs: [
                {
                  name: "drawId",
                  type: "core::integer::u64",
                },
              ],
              outputs: [
                {
                  type: "core::integer::u64",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "GetJackpotEntryEndBlock",
              inputs: [
                {
                  name: "drawId",
                  type: "core::integer::u64",
                },
              ],
              outputs: [
                {
                  type: "core::integer::u64",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "GetJackpotEntryIsActive",
              inputs: [
                {
                  name: "drawId",
                  type: "core::integer::u64",
                },
              ],
              outputs: [
                {
                  type: "core::bool",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "GetJackpotEntryIsCompleted",
              inputs: [
                {
                  name: "drawId",
                  type: "core::integer::u64",
                },
              ],
              outputs: [
                {
                  type: "core::bool",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "GetStarkPlayContractAddress",
              inputs: [],
              outputs: [
                {
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "GetStarkPlayVaultContractAddress",
              inputs: [],
              outputs: [
                {
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "GetCurrentDrawId",
              inputs: [],
              outputs: [
                {
                  type: "core::integer::u64",
                },
              ],
              state_mutability: "view",
            },
          ],
        },
        {
          type: "impl",
          name: "OwnableImpl",
          interface_name: "openzeppelin_access::ownable::interface::IOwnable",
        },
        {
          type: "interface",
          name: "openzeppelin_access::ownable::interface::IOwnable",
          items: [
            {
              type: "function",
              name: "owner",
              inputs: [],
              outputs: [
                {
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "transfer_ownership",
              inputs: [
                {
                  name: "new_owner",
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "renounce_ownership",
              inputs: [],
              outputs: [],
              state_mutability: "external",
            },
          ],
        },
        {
          type: "constructor",
          name: "constructor",
          inputs: [
            {
              name: "owner",
              type: "core::starknet::contract_address::ContractAddress",
            },
            {
              name: "strkPlayContractAddress",
              type: "core::starknet::contract_address::ContractAddress",
            },
            {
              name: "strkPlayVaultContractAddress",
              type: "core::starknet::contract_address::ContractAddress",
            },
          ],
        },
        {
          type: "event",
          name: "openzeppelin_access::ownable::ownable::OwnableComponent::OwnershipTransferred",
          kind: "struct",
          members: [
            {
              name: "previous_owner",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "key",
            },
            {
              name: "new_owner",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "key",
            },
          ],
        },
        {
          type: "event",
          name: "openzeppelin_access::ownable::ownable::OwnableComponent::OwnershipTransferStarted",
          kind: "struct",
          members: [
            {
              name: "previous_owner",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "key",
            },
            {
              name: "new_owner",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "key",
            },
          ],
        },
        {
          type: "event",
          name: "openzeppelin_access::ownable::ownable::OwnableComponent::Event",
          kind: "enum",
          variants: [
            {
              name: "OwnershipTransferred",
              type: "openzeppelin_access::ownable::ownable::OwnableComponent::OwnershipTransferred",
              kind: "nested",
            },
            {
              name: "OwnershipTransferStarted",
              type: "openzeppelin_access::ownable::ownable::OwnableComponent::OwnershipTransferStarted",
              kind: "nested",
            },
          ],
        },
        {
          type: "event",
          name: "openzeppelin_security::reentrancyguard::ReentrancyGuardComponent::Event",
          kind: "enum",
          variants: [],
        },
        {
          type: "event",
          name: "contracts::Lottery::Lottery::TicketPurchased",
          kind: "struct",
          members: [
            {
              name: "drawId",
              type: "core::integer::u64",
              kind: "key",
            },
            {
              name: "player",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "key",
            },
            {
              name: "ticketId",
              type: "core::felt252",
              kind: "data",
            },
            {
              name: "numbers",
              type: "core::array::Array::<core::integer::u16>",
              kind: "data",
            },
            {
              name: "ticketCount",
              type: "core::integer::u32",
              kind: "data",
            },
            {
              name: "timestamp",
              type: "core::integer::u64",
              kind: "data",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::Lottery::Lottery::BulkTicketPurchase",
          kind: "struct",
          members: [
            {
              name: "drawId",
              type: "core::integer::u64",
              kind: "key",
            },
            {
              name: "player",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "key",
            },
            {
              name: "quantity",
              type: "core::integer::u8",
              kind: "data",
            },
            {
              name: "totalPrice",
              type: "core::integer::u256",
              kind: "data",
            },
            {
              name: "timestamp",
              type: "core::integer::u64",
              kind: "data",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::Lottery::Lottery::BulkTicketPurchase",
          kind: "struct",
          members: [
            {
              name: "drawId",
              type: "core::integer::u64",
              kind: "key",
            },
            {
              name: "player",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "key",
            },
            {
              name: "quantity",
              type: "core::integer::u8",
              kind: "data",
            },
            {
              name: "totalPrice",
              type: "core::integer::u256",
              kind: "data",
            },
            {
              name: "timestamp",
              type: "core::integer::u64",
              kind: "data",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::Lottery::Lottery::DrawCompleted",
          kind: "struct",
          members: [
            {
              name: "drawId",
              type: "core::integer::u64",
              kind: "data",
            },
            {
              name: "winningNumbers",
              type: "core::array::Array::<core::integer::u16>",
              kind: "data",
            },
            {
              name: "accumulatedPrize",
              type: "core::integer::u256",
              kind: "data",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::Lottery::Lottery::PrizeClaimed",
          kind: "struct",
          members: [
            {
              name: "drawId",
              type: "core::integer::u64",
              kind: "key",
            },
            {
              name: "player",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "key",
            },
            {
              name: "ticketId",
              type: "core::felt252",
              kind: "data",
            },
            {
              name: "prizeAmount",
              type: "core::integer::u256",
              kind: "data",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::Lottery::Lottery::UserTicketsInfo",
          kind: "struct",
          members: [
            {
              name: "player",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "key",
            },
            {
              name: "drawId",
              type: "core::integer::u64",
              kind: "data",
            },
            {
              name: "tickets",
              type: "core::array::Array::<contracts::Lottery::Ticket>",
              kind: "data",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::Lottery::Lottery::JackpotIncreased",
          kind: "struct",
          members: [
            {
              name: "drawId",
              type: "core::integer::u64",
              kind: "key",
            },
            {
              name: "previousAmount",
              type: "core::integer::u256",
              kind: "data",
            },
            {
              name: "newAmount",
              type: "core::integer::u256",
              kind: "data",
            },
            {
              name: "timestamp",
              type: "core::integer::u64",
              kind: "data",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::Lottery::Lottery::InvalidDrawIdAttempted",
          kind: "struct",
          name: "contracts::Lottery::Lottery::InvalidDrawIdAttempted",
          kind: "struct",
          members: [
            {
              name: "caller",
              name: "caller",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "data",
              kind: "data",
            },
            {
              name: "attempted_draw_id",
              name: "attempted_draw_id",
              type: "core::integer::u64",
              kind: "data",
              kind: "data",
            },
            {
              name: "current_draw_id",
              name: "current_draw_id",
              type: "core::integer::u64",
              kind: "data",
            },
            {
              name: "function_name",
              type: "core::felt252",
              kind: "data",
              kind: "data",
            },
            {
              name: "function_name",
              type: "core::felt252",
              kind: "data",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::Lottery::Lottery::DrawValidationFailed",
          name: "contracts::Lottery::Lottery::DrawValidationFailed",
          kind: "struct",
          members: [
            {
              name: "draw_id",
              type: "core::integer::u64",
              kind: "data",
              name: "draw_id",
              type: "core::integer::u64",
              kind: "data",
            },
            {
              name: "reason",
              type: "core::felt252",
              kind: "data",
              name: "reason",
              type: "core::felt252",
              kind: "data",
            },
            {
              name: "caller",
            {
              name: "caller",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "data",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::Lottery::Lottery::EmergencyReentrancyGuardReset",
          kind: "struct",
          members: [
            {
              name: "caller",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "data",
            },
            {
              name: "timestamp",
              type: "core::integer::u64",
              kind: "data",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::Lottery::Lottery::Event",
          name: "contracts::Lottery::Lottery::Event",
          kind: "enum",
          variants: [
            {
              name: "OwnableEvent",
              type: "openzeppelin_access::ownable::ownable::OwnableComponent::Event",
              kind: "flat",
              name: "OwnableEvent",
              type: "openzeppelin_access::ownable::ownable::OwnableComponent::Event",
              kind: "flat",
            },
            {
              name: "ReentrancyGuardEvent",
              type: "openzeppelin_security::reentrancyguard::ReentrancyGuardComponent::Event",
              kind: "flat",
            },
            {
              name: "TicketPurchased",
              type: "contracts::Lottery::Lottery::TicketPurchased",
              kind: "nested",
            },
            {
              name: "BulkTicketPurchase",
              type: "contracts::Lottery::Lottery::BulkTicketPurchase",
              kind: "nested",
            },
            {
              name: "DrawCompleted",
              type: "contracts::Lottery::Lottery::DrawCompleted",
              kind: "nested",
            },
            {
              name: "PrizeClaimed",
              type: "contracts::Lottery::Lottery::PrizeClaimed",
              kind: "nested",
            },
            {
              name: "UserTicketsInfo",
              type: "contracts::Lottery::Lottery::UserTicketsInfo",
              kind: "nested",
            },
            {
              name: "JackpotIncreased",
              type: "contracts::Lottery::Lottery::JackpotIncreased",
              kind: "nested",
            },
            {
              name: "InvalidDrawIdAttempted",
              type: "contracts::Lottery::Lottery::InvalidDrawIdAttempted",
              kind: "nested",
            },
            {
              name: "DrawValidationFailed",
              type: "contracts::Lottery::Lottery::DrawValidationFailed",
              kind: "nested",
            },
            {
              name: "EmergencyReentrancyGuardReset",
              type: "contracts::Lottery::Lottery::EmergencyReentrancyGuardReset",
              kind: "nested",
            },
          ],
        },
      ],
      classHash:
        "0x4b85b028aa19c75137522e318016dca1c25182c0b51364ba62b8de0b6d553de",
    },
  },
} as const;

export default deployedContracts;
