name: Next.js CI

on:
  push:
    paths:
      - "packages/snfoundry/contracts/**"
      - "packages/nextjs/**"
  pull_request:
    branches:
      - main
    paths:
      - "packages/nextjs/**"
      - "packages/snfoundry/contracts/**"

jobs:
  ci:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [lts/*]

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Install scarb
        run: curl --proto '=https' --tlsv1.2 -sSf https://docs.swmansion.com/scarb/install.sh | sh -s -- -v 2.9.2

      - name: Install snfoundryup
        run: curl -L https://raw.githubusercontent.com/foundry-rs/starknet-foundry/master/scripts/install.sh | sh

      - name: Install snforge
        run: snfoundryup -v 0.34.0

      - name: Build snfoundry dependencies
        run: cd packages/snfoundry && yarn install --immutable && yarn compile

      - name: Validate Scarb.toml configuration
        run: |
          if [ ! -f ./Scarb.toml ]; then
            echo "Error: Scarb.toml is missing in the current directory" && exit 1
          fi
          if ! grep -q '\[profile.dev.cairo\]' ./Scarb.toml; then
            echo "Error: Missing [profile.dev.cairo] section in Scarb.toml" && exit 1
          fi
          if ! grep -q 'unstable-add-statements-code-locations-debug-info = true' ./Scarb.toml; then
            echo "Error: Missing unstable-add-statements-code-locations-debug-info setting in Scarb.toml" && exit 1
          fi
          if ! grep -q 'inlining-strategy = "avoid"' ./Scarb.toml; then
            echo "Error: Missing inlining-strategy setting in Scarb.toml" && exit 1
          fi
          echo "Scarb.toml validation successful: Configuration for coverage is present"
        working-directory: ./packages/snfoundry/contracts

      - name: Run snforge tests
        run: snforge test --coverage
        working-directory: ./packages/snfoundry/contracts

      - name: Setup node env
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: "yarn"
          #cache-dependency-path: packages/nextjs/yarn.lock

      - name: Install dependencies (Next.js)
        run: yarn install --immutable
        working-directory: ./packages/nextjs

      - name: Install root dependencies
        run: yarn install --immutable

      - name: Check Code Format
        run: yarn format:check

      - name: Run Next.js lint
        run: yarn next:lint --max-warnings=0
        working-directory: ./packages/nextjs

      - name: Check typings on Next.js
        run: yarn next:check-types
        working-directory: ./packages/nextjs

      - name: Run Next.js tests
        run: yarn test run
        working-directory: ./packages/nextjs

      - name: Build Next.js project
        run: yarn build
        working-directory: ./packages/nextjs
