name: Next.js CI

on:
  push:
    paths:
      - "packages/snfoundry/contracts/**"
      - "packages/nextjs/**"
  pull_request:
    branches:
      - main
    paths:
      - "packages/nextjs/**"
      - "packages/snfoundry/contracts/**"

jobs:
  ci:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [18]

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Install scarb
        run: curl --proto '=https' --tlsv1.2 -sSf https://docs.swmansion.com/scarb/install.sh | sh -s -- -v 2.9.2

      - name: Verify scarb installation
        run: |
          scarb --version
          echo "Scarb installation directory: $(which scarb)"

      - name: Install snfoundryup
        run: curl -L https://raw.githubusercontent.com/foundry-rs/starknet-foundry/master/scripts/install.sh | sh

      - name: Install snforge
        run: snfoundryup -v 0.34.0

      - name: Verify snforge installation
        run: |
          snforge --version
          echo "SNforge installation directory: $(which snforge)"

      - name: Clear build cache
        run: |
          rm -rf ~/.cache/scarb
          rm -rf ~/.cache/snfoundry
          echo "Cleared build caches"

      # - name: Run snforge tests
      #   run: snforge test --coverage
      #   working-directory: ./packages/snfoundry/contracts

      - name: Build snfoundry dependencies
        run: cd packages/snfoundry && yarn install --immutable && yarn compile

      - name: Setup node env
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: "yarn"
          #cache-dependency-path: packages/nextjs/yarn.lock

      - name: Clear Yarn Cache
        run: yarn cache clean --all

      - name: Install dependencies (Next.js)
        run: |
          for i in {1..3}; do
            yarn install --immutable --force && break
            echo "Retrying yarn install (attempt $i of 3)..."
            sleep 10
          done
        working-directory: ./packages/nextjs

      - name: Install root dependencies
        run: yarn install --immutable

      - name: Check Code Format
        run: yarn format:check

      - name: Run Next.js lint
        run: yarn next:lint --max-warnings=0
        working-directory: ./packages/nextjs

      - name: Check typings on Next.js
        run: yarn next:check-types
        working-directory: ./packages/nextjs

      - name: Run Next.js tests
        run: yarn test run
        working-directory: ./packages/nextjs

      - name: Build Next.js project
        run: |
          set -x
          yarn build
        working-directory: ./packages/nextjs
