name: Snfoundry Contracts CI

on:
  push:
    branches: [dev]
    paths:
      - "packages/snfoundry/contracts/**"
  pull_request:
    branches: [dev]
    paths:
      - "packages/snfoundry/contracts/**"
      - ".github/workflows/**"

jobs:
  build-and-test-contracts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup scarb
        uses: software-mansion/setup-scarb@v1
        with:
          tool-versions: ./.tool-versions
          scarb-lock: ./packages/snfoundry/contracts/Scarb.lock

      - name: Setup snfoundry
        uses: foundry-rs/setup-snfoundry@v3
        with:
          tool-versions: ./.tool-versions

      - name: Compile contracts (treat warnings as errors)
        run: |
          export RUSTFLAGS="-D warnings"
          scarb build
        working-directory: ./packages/snfoundry/contracts

      - name: List tests
        run: snforge test -- --list
        working-directory: ./packages/snfoundry/contracts

      - name: Run snfoundry tests (verbose + logs, warnings as errors)
        env:
          RUST_BACKTRACE: 1
          SNFORGE_FORMAT: pretty
          RUSTFLAGS: "-D warnings"
        run: snforge test -- -v --print-logs
        working-directory: ./packages/snfoundry/contracts
